### ISSUE TITLE
raise BadZipfile, "File is not a zip file"

### ISSUE THREAD

**Issue by den-run-ai** [lepisma/pipwin#14]
```
C:\Users\>pipwin install pyqt4
C:\Users\\.pipwin
Package found in cache
Downloading package . . .
http://www.lfd.uci.edu/~gohlke/pythonlibs/AuDkqpdh/PyQt4-4.11.4-cp27-none-win32.
whl
PyQt4-4.11.4-cp27-none-win32.whl
0%  100%
[]Processing c:\users\\pipwin\pyqt4-4.11.4-cp27-none-win32.whl
Exception:
Traceback (most recent call last):
  File "c:\python\python27\lib\site-packages\pip\basecommand.py", line 211, in m
ain
    status = self.run(options, args)
  File "c:\python\python27\lib\site-packages\pip\commands\install.py", line 305,
 in run
    wb.build(autobuilding=True)
  File "c:\python\python27\lib\site-packages\pip\wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\python\python27\lib\site-packages\pip\req\req_set.py", line 334, in p
repare_files
    functools.partial(self._prepare_file, finder))
  File "c:\python\python27\lib\site-packages\pip\req\req_set.py", line 321, in _
walk_req_to_install
    more_reqs = handler(req_to_install)
  File "c:\python\python27\lib\site-packages\pip\req\req_set.py", line 491, in _
prepare_file
    session=self.session)
  File "c:\python\python27\lib\site-packages\pip\download.py", line 814, in unpa
ck_url
    unpack_file_url(link, location, download_dir)
  File "c:\python\python27\lib\site-packages\pip\download.py", line 723, in unpa
ck_file_url
    unpack_file(from_path, location, content_type, link)
  File "c:\python\python27\lib\site-packages\pip\utils\__init__.py", line 645, i
n unpack_file
    flatten=not filename.endswith('.whl')
  File "c:\python\python27\lib\site-packages\pip\utils\__init__.py", line 531, i
n unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "c:\python\python27\lib\zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "c:\python\python27\lib\zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file

C:\Users\>pipwin install pyqt
C:\Users\\.pipwin
Did you mean any of these ?

 * pyqtdesignerplugins
 * pyqtgraph
 * pyqt4


C:\Users\>


```

**Comment by edbordin** [comment]
#24 may fix this

**Comment by SmartManoj** [comment]
duplicate #4

> #24 may fix this

didn't

**Comment by samapriya** [comment]
This is occurring again after updating from 0.4.5 to 0.4.6

**Comment by SmartManoj** [comment]
size of the wheel?
install whl from cmd
