### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by eromoe** [lepisma/pipwin#15]
`pipwin search cv`  get error:

```
Building cache. Hang on . . .
c:\python27\lib\site-packages\bs4\__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the bes
t available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another syst
em, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pipwin.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\pipwin\command.py", line 65, in main
    cache = pipwin.PipwinCache()
  File "c:\python27\lib\site-packages\pipwin\pipwin.py", line 181, in __init__
    self.data = build_cache()
  File "c:\python27\lib\site-packages\pipwin\pipwin.py", line 87, in build_cache
    mlstr = jsfun[0].split("(")[1].strip()[1:-2]
IndexError: list index out of range
```

run second time , this error disappear, wired...

**Comment by SmartManoj** [comment]
Can't reproduce
