### ISSUE TITLE
pipwin install rtree 404 error

### ISSUE THREAD

**Issue by iamtekson** [lepisma/pipwin#48]
I tried to install rtree through ```pip install rtree```, But it throws the error code 404 not found as below. I tried to install other packages too, But the error message is same for all. Can anyone help?

```bash
https://download.lfd.uci.edu/pythonlibs/w3jqiv8s/Rtree-0.9.4-cp38-cp38-win_amd64.whl
Rtree-0.9.4-cp38-cp38-win_amd64.whl
Traceback (most recent call last):
  File "C:\Program Files\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\SDSS\1. code\django\venv\Scripts\pipwin.exe\__main__.py", line 7, in <module>
  File "f:\sdss\1. code\django\venv\lib\site-packages\pipwin\command.py", line 98, in main
    cache.install(package)
  File "f:\sdss\1. code\django\venv\lib\site-packages\pipwin\pipwin.py", line 300, in install
    wheel_file = self.download(requirement)
  File "f:\sdss\1. code\django\venv\lib\site-packages\pipwin\pipwin.py", line 294, in download
    return self._download(requirement, dest)
  File "f:\sdss\1. code\django\venv\lib\site-packages\pipwin\pipwin.py", line 290, in _download
    obj.start()
  File "f:\sdss\1. code\django\venv\lib\site-packages\pySmartDL\pySmartDL.py", line 257, in start
    urlObj = urllib.request.urlopen(req, timeout=self.timeout)
  File "C:\Program Files\python\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\python\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Program Files\python\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Program Files\python\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Program Files\python\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Program Files\python\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by iamtekson** [comment]
`pipwin refresh` solved my problem thank you
