### ISSUE TITLE
Everything Worked before soem days, Now Giving Error

### ISSUE THREAD

**Issue by Rasesh2005** [lepisma/pipwin#49]
## Error:
```bash
Downloading package . . .
https://download.lfd.uci.edu/pythonlibs/w3jqiv8s/PyAudio-0.2.11-cp38-cp38-win_amd64.whl
PyAudio-0.2.11-cp38-cp38-win_amd64.whl
Traceback (most recent call last):
  File "E:\Python Versions\Python3.8.6\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Python Versions\Python3.8.6\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\PythonProjects\env\Scripts\pipwin.exe\__main__.py", line 7, in <module>
  File "d:\pythonprojects\env\lib\site-packages\pipwin\command.py", line 98, in main
    cache.install(package)
  File "d:\pythonprojects\env\lib\site-packages\pipwin\pipwin.py", line 300, in install
    wheel_file = self.download(requirement)
  File "d:\pythonprojects\env\lib\site-packages\pipwin\pipwin.py", line 294, in download
    return self._download(requirement, dest)
  File "d:\pythonprojects\env\lib\site-packages\pipwin\pipwin.py", line 290, in _download
    obj.start()
  File "d:\pythonprojects\env\lib\site-packages\pySmartDL\pySmartDL.py", line 267, in start
    urlObj = urllib.request.urlopen(req, timeout=self.timeout, context=self.context)
  File "E:\Python Versions\Python3.8.6\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Python Versions\Python3.8.6\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "E:\Python Versions\Python3.8.6\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "E:\Python Versions\Python3.8.6\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "E:\Python Versions\Python3.8.6\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "E:\Python Versions\Python3.8.6\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by lepisma** [comment]
did you try refreshing the cache? `pipwin refresh`

**Comment by Rasesh2005** [comment]
Yes I tried, And ya i recently updated to python 3.9, Is it causing the issue???

**Comment by Rasesh2005** [comment]
Now after i refreshed and tried 10 to 15 times, It is working.... But before closing the issue, Can u plz tell in brief what caused this issue??

**Comment by iamtekson** [comment]
I also suffer a lot from this error. Now `pipwin refresh` solved my error.
