### ISSUE TITLE
Installing PyAudio Results in 404 Error

### ISSUE THREAD

**Issue by juanponcedeleon** [lepisma/pipwin#55]
when i run `pipwin install pyaudio`, it gives me the following error:

```
Traceback (most recent call last):
  File "C:\Users\jmast\AppData\Local\Programs\Python\Python39\Scripts\pipwin-script.py", line 33, in <module>
    sys.exit(load_entry_point('pipwin==0.5.1', 'console_scripts', 'pipwin')())
  File "c:\users\jmast\appdata\local\programs\python\python39\lib\site-packages\pipwin\command.py", line 103, in main
    cache.install(package)
  File "c:\users\jmast\appdata\local\programs\python\python39\lib\site-packages\pipwin\pipwin.py", line 300, in install
    wheel_file = self.download(requirement)
  File "c:\users\jmast\appdata\local\programs\python\python39\lib\site-packages\pipwin\pipwin.py", line 294, in download
    return self._download(requirement, dest)
  File "c:\users\jmast\appdata\local\programs\python\python39\lib\site-packages\pipwin\pipwin.py", line 290, in _download
    obj.start()
  File "c:\users\jmast\appdata\local\programs\python\python39\lib\site-packages\pySmartDL\pySmartDL.py", line 267, in start
    urlObj = urllib.request.urlopen(req, timeout=self.timeout, context=self.context)
  File "c:\users\jmast\appdata\local\programs\python\python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\jmast\appdata\local\programs\python\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\users\jmast\appdata\local\programs\python\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\users\jmast\appdata\local\programs\python\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\users\jmast\appdata\local\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\users\jmast\appdata\local\programs\python\python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by samapriya** [comment]
Hi @JMasterBoi 
Run a pipwin refresh. Pipwin sources the URL from https://www.lfd.uci.edu/~gohlke/pythonlibs/ and pipwin refresh makes sure the updated URL is sourced since it can change quite frequently

so try

```
pipwin refresh
pip install pyaudio
```

**Comment by juanponcedeleon** [comment]
> Hi @JMasterBoi
> Run a pipwin refresh. Pipwin sources the URL from https://www.lfd.uci.edu/~gohlke/pythonlibs/ and pipwin refresh makes sure the updated URL is sourced since it can change quite frequently
> 
> so try
> 
> ```
> pipwin refresh
> pip install pyaudio
> ```

thank you that worked perfectly 👍
