### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by themixray** [lepisma/pipwin#61]
this happens when I try to install pyaudio
```
Package `pyaudio` found in cache
Downloading package . . .
https://download.lfd.uci.edu/pythonlibs/y2rycu7g/PyAudio-0.2.11-cp37-cp37m-win32.whl
PyAudio-0.2.11-cp37-cp37m-win32.whl
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\Scripts\pipwin-script.py", line 11, in <module>
    load_entry_point('pipwin==0.5.1', 'console_scripts', 'pipwin')()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pipwin\command.py", line 103, in main
    cache.install(package)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pipwin\pipwin.py", line 300, in install
    wheel_file = self.download(requirement)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pipwin\pipwin.py", line 294, in download
    return self._download(requirement, dest)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pipwin\pipwin.py", line 290, in _download
    obj.start()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pySmartDL\pySmartDL.py", line 267, in start
    urlObj = urllib.request.urlopen(req, timeout=self.timeout, context=self.context)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by Soebb** [comment]
same for me and not be solved even after `pipwin refresh`
