### ISSUE TITLE
JSONDecodeError on Python3.5

### ISSUE THREAD

**Issue by anntzer** [lepisma/pipwin#8]
Python3.5 from recent miniconda, pipwin 0.2.3:

```
$ pipwin search cv
C:\Users\Darwin\.pipwin
Traceback (most recent call last):
  File "c:\users\darwin\miniconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\darwin\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Darwin\Miniconda3\Scripts\pipwin.exe\__main__.py", line 9, in <module>
  File "c:\users\darwin\miniconda3\lib\site-packages\pipwin\command.py", line 39, in main
    cache = pipwin.PipwinCache()
  File "c:\users\darwin\miniconda3\lib\site-packages\pipwin\pipwin.py", line 174, in __init__
    self.data = json.loads(cache_dump)
  File "c:\users\darwin\miniconda3\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "c:\users\darwin\miniconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\darwin\miniconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by lepisma** [comment]
Have you tried cache reset?
`pipwin refresh`

**Comment by anntzer** [comment]
Works after reinstalling, not sure what happened.

**Comment by lepisma** [comment]
Cool

**Comment by lepisma** [comment]
By the way, did you by any chance did `pipwin refresh` in between the process ?

**Comment by lepisma** [comment]
By the way, did you by any chance do `pipwin refresh` in between the process ?

**Comment by anntzer** [comment]
Nope, it came down to unhappily uninstalling pipwin and trying again the next day.
